{% set name = "mpart" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MeasureTransport/MParT/archive/{{ version }}.tar.gz
  sha256: 80262cc283131b0203b92b2bf35480153f8c669c9b01893e0db471c1d55bebc9
  
build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - make
  host:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - make
    - python
    - numpy
    - eigen >=3.3.9
    - pybind11
  run:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - make
    - python
    - {{ pin_compatible('numpy') }}
    - eigen >=3.3.9
  
test:
  imports:
    - mpart

about:
  home: https://github.com/MeasureTransport/MParT
  summary: 'Performance portable implementations of monotone parameterizations and transport maps.'
  description: 'MParT is a library for monotone parameterizations written in c++ with bindings to python, julia, and matlab.  It is designed as a core building block for research and software invovling transport maps and isotonic regression.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://measuretransport.github.io/MParT/
  dev_url: https://github.com/MeasureTransport/MParT

extra:
  recipe-maintainers:
    - mparno
    - dannys4
    - michael-c-brennan
    - bonh
    - rubiop
